	<!-- <div id="mobile-footer-wrapper" class="visible-xs visible-sm">
		
		<div id="mobile-header-footer-copy" class="mobile-footer">
			<h2>newsletter sign up</h2>
			<hr class="small">			
			<p>Join our Gryphon Tea Family and be the first to learn about our latest news, enjoy exclusive deals and invites to events!</p>

			<div class="search">
				<input type="text" name="subscribe_email" placeholder="Enter your email address" />
				<button class="signup subscribe_newsletter"><i class="fa fa-check"></i> <span>Sign up</span></button>
				<span class='newsletter_ajax_loader' style='display:none'><img src='<?php echo $this->getSkinUrl('images/content/opc-ajax-loader.gif')?>'/></span>
            	<span class="ajax_msg italic"></span>
			</div>

			<hr class="dotted">

			<h2>FOLLOW US</h2>
			<hr class="small">
			<ul class="share-ctas">
				<li><a href="https://instagram.com/gryphontea/" target="_blank" class="instagram"><i class="fa fa-instagram"></i></a></li>
				<li><a href="https://www.pinterest.com/gryphontea/" target="_blank" class="pintrest"><i class="fa fa-pinterest"></i></a></li>
				<li><a href="https://www.facebook.com/gryphonteacompany" target="_blank" class="facebook"><i class="fa fa-facebook"></i></a></li>
				<li><a href="https://www.linkedin.com/company/gryphon-tea-company" target="_blank" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
				<li><a href="https://www.youtube.com/channel/UCrKNQcT3PHO-o_vQBMUlH8Q/videos" target="_blank" class="youtube"><i class="fa fa-youtube"></i></a></li>
				<li><a href="https://plus.google.com/+Gryphonteacompany/posts" target="_blank" class="google-plus"><i class="fa fa-google-plus"></i></a></li>
			</ul>

			<div class="copywrite">
				<h6>&copy; <?php echo date("Y"); ?> GRYPHON TEA COMPANY.</h6>
				<p>All material on this site is copyrighted by Gryphon Tea Company. Gryphon Tea Company® is a registered trademark. No images or copy on this site may be used without written permission by Gryphon Tea Company.</p>	
			</div>

		</div>
				
	</div> -->

	<footer id="desktop-footer" class="visible-md visible-lg">
	  <div id="desktop-footer-ctas-container">
	    <div class="container-fluid">
	      <div class="row">
					<div class="col-md-2">
	          <h5>About Monogram</h5>
	          <ul>
	            <li><a href="<?php echo $this->getUrl('experience'); ?>">Experience Monogram</a></li>
	            <li><a href="<?php echo $this->getUrl('/'); ?>#graph/cherry-japonais">Layering Suggestions</a></li>
	            <li><a href="<?php echo $this->getUrl('tea-layering'); ?>">Tea Layering</a></li>	            
	            <li><a href="<?php echo $this->getUrl('tea-matrix'); ?>">Tea Matrix</a></li>
	            <li><a href="<?php echo $this->getUrl('monolog'); ?>">Monolog</a></li>
	          </ul>
	        </div>
	        <div class="col-md-2">
	          <h5>Shop</h5>
	          <?php $store_category = Mage::getModel('catalog/category')->loadByAttribute('name', 'Store'); ?>
	          <ul>
	            <li><a href="<?php echo $store_category->getUrl(); ?>">Tea Store</a></li>
	            <!-- <li><a href="<?php echo $this->getUrl('subscription'); ?>">Subscription</a></li> -->
	            <li><a href="<?php echo $this->getUrl('monogram-service'); ?>">Monogram Services</a></li>	
	          </ul>
	        </div>
	        <div class="col-md-2">
	          <h5>Order Information</h5>
	          <ul>
	            <li><a href="<?php echo $this->getUrl('customer/account/create/') ?>">Account Registration</a></li>
	            <li><a href="<?php echo $this->getUrl('faq'); ?>">Frequently Asked Questions</a></li>
	            <li><a href="<?php echo $this->getUrl('shipping-info'); ?>">Shipping Information</a></li>
	            <li><a href="http://www.trackntrace.com.sg/">Track Order</a></li>
	          </ul>
	        </div>
	        <div class="col-md-2">
	          <div class="footer-follow-us-section">
	            <h5>Follow Us</h5>
	            <ul class="social-media-icons">
	              <li><a href="https://www.twitter.com/monogramtea"><i class="fa fa-twitter"></i></a></li>
	              <li><a href="https://www.facebook.com/monogramtea"><i class="fa fa-facebook"></i></a></li>
	              <li><a href="https://instagram.com/monogramtea/"><i class="fa fa-instagram"></i></a></li>
	            </ul>

	            <h5>Contact Us</h5>
	            <a href="mailto:contact@monogram.com.sg">contact@monogram.com.sg</a>
	            <a href="tel:6512345678" class="telephone">+65 1234 5678</a>
	          </div>
	        </div>
	        <div class="col-md-3 col-md-offset-1">
	          <h5>Newsletter</h5>
	          <p>Get the latest news, product <br> announcements, promotions, and more!</p>
	        
	          <div id="footer-newsletter-input">
	            <input type="text" name="subscribe_email" id="subscribe_email" placeholder="Enter your email address" />
	            <a href="#" class="signup subscribe_newsletter footer-newsletter-send-btn"><i class="fa fa-paper-plane" aria-hidden="true"></i></a>
	            <span class='newsletter_ajax_loader' style='display:none'><img src='<?php echo $this->getSkinUrl('images/icons/spin.svg')?>'/></span>        			
	          </div>
	          <span class="ajax_msg italic"></span>
	        </div>
	      </div>
	     </div>
	  </div>
	  <div id="desktop-footer-logo-tnc-container">
	    <div class="container-fluid">
	      <div class="col-md-4">
	        <a href="<?php echo $this->getUrl('') ?>">
	          <span id="desktop-footer-logo"></span>
	          <h5 id="monogram-name">monogram by gryphon tea company</h5>
	        </a>
	      </div>
	      <div class="col-md-3 col-md-offset-5">
	        <ul>
	          <li><a href="<?php echo $this->getUrl('privacy-policy'); ?>">Privacy Policy</a></li>
	          <li><a href="<?php echo $this->getUrl('terms-and-conditions'); ?>">Terms & Condition</a></li>
	        </ul>
	      </div>
	    </div>
	  </div>
 	</footer>
	<script>
		jQuery(document).ready(function($){
			$('#subscribe_email').keypress(function(event){
				var keycode = (event.keyCode ? event.keyCode : event.which);
				if(keycode == '13') 
					$('.subscribe_newsletter').trigger('click');
			});
			$('.subscribe_newsletter').on('click', function(e){
				var subscribe_email = $('#subscribe_email').val();

				jQuery('.newsletter_ajax_loader').show();

				var request = $.ajax({
				  	url: "<?php echo $this->getUrl('discovertea/index/subscribe', array('_secure'=>true)) ?>",
				  	method: "POST",
				  	data: { subscribe_email : subscribe_email },
				  	dataType: "html"
				});
				 
				request.done(function( msg ) {
					var message = JSON.parse(msg);
					console.log(message);
					jQuery('.newsletter_ajax_loader').hide();
					if(message.error_messages)
						jQuery('span.ajax_msg').html('<p>'+message.error_messages+'</p>').show().delay(5000).fadeOut();				  		
				  	else
						jQuery('span.ajax_msg').html('<p>Successfully subscribed to newsletter</p>').show().delay(5000).fadeOut();
				});
			});
		});
	</script>