<div id="under-construction-disclaimer">
  <p>This site is under-construction</p>
</div>








<!--
   __  __  ___  ____ ___ _     _____
  |  \/  |/ _ \| __ )_ _| |   | ____|
  | |\/| | | | |  _ \| || |   |  _|
  | |  | | |_| | |_) | || |___| |___
  |_|  |_|\___/|____/___|_____|_____|

-->






<article id="home-mobile-landing-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="default-copy white-version">
          <h1>The art of tea layering</h1>
          <p>Excite the palate and discover a world of simplexity tea flavours with Monogram. Exuding class and sophistication, yet playful and dynamic, explore the art of tea layering with every cup. With no two brews tasting the same, curate a personal unique identity with the world’s finest handpicked tea leaves and herbs. Get hands on and experimental with Monogram, layering the silken sachets to harmonious perfection. With each sachet carefully selected to complement each other, half the fun is to discover your very own brew. More importantly, the special bond that comes with each tea layering experience.</p>

          <h4>tea layering suggestion</h4>
          <!-- insert graph here -->

          <h2>earl grey neroli + Shiso mint</h2>
          <p>Suspendisse in enim nisl. Duis nec lacus magna. Curabitur tempus metus in libero. lacinia posuere. Duis accumsan bibendum dapibus. </p>
          

          <div class="cta-container">
            <a href="" class="square-cta">buy both teas</a>
            <a href="" class="square-cta">see more layering</a>
          </div>

          <h4>popular tea layering</h4>

          <div class="something">
            <h2>cherry japonais + kashmeretm</h2>
            <h6>by monogram</h6>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada massa...</p>
          </div>

          <p>visit store</p>


        </div>
      </div>
    </div>
  </div>
</article> <!-- home-mobile-landing-section -->



<article id="home-mobile-tea-layering-section">
  <p>this is the tea layering section</p>
</article> <!-- home-mobile-tea-layering-section -->











<!--
    ____ ____      _    ____  _   _
   / ___|  _ \    / \  |  _ \| | | |
  | |  _| |_) |  / _ \ | |_) | |_| |
  | |_| |  _ <  / ___ \|  __/|  _  |
   \____|_| \_\/_/   \_\_|   |_| |_|

-->


<article id="tea-layering-detail-graph-section">


  <div id="tea-layering-graph-mobile">

    <div id="combination-graph-text-container">
    </div>
    <div id="combination-graph-svg-container">
      <div id="combination-graph-svg"></div>
    </div>

    <div id="combination-graph-label">
      <div class="graph-label-image graph-label-wood"></div>
      <div class="graph-label-image graph-label-savoury"></div>
      <div class="graph-label-image graph-label-herbaceous"></div>
      <div class="graph-label-image graph-label-floral"></div>
      <div class="graph-label-image graph-label-nutty"></div>
      <div class="graph-label-image graph-label-dairy"></div>
      <div class="graph-label-image graph-label-minerality"></div>
      <div class="graph-label-image graph-label-citrus"></div>
      <div class="graph-label-image graph-label-stone-fruit"></div>
      <div class="graph-label-image graph-label-red-fruit"></div>
      <div class="graph-label-image graph-label-sweet"></div>
    </div>

  </div>
</article>


<!--
    ____ ___  ______   __
   / ___/ _ \|  _ \ \ / /
  | |  | | | | |_) \ V /
  | |__| |_| |  __/ | |
   \____\___/|_|    |_|

 -->


<article id="tea-layering-detail-copy-section">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">

        <div class="graph-selection-tea-mobile">

          <div class="graph-selection-title">
            <h4>layering suggestion <span class="number">1/4</span></h4>
          </div>

          

          <div class="graph-selection-name">
            <div id="graph-selection-name-01">
              <h2><span style="color:#c0cdd5">Earl Grey</span> <span style="color:#d8d1ca">Neroli</span></h2>
            </div>
            <div id="graph-selection-name-02">
              <div class="plus-sign">+</div>
              <h2><span style="color:#c7c89b">Shiso</span> <span style="color:#bcc4b9">Mint</span></h2>
            </div>
          </div>

          <div class="tea-copy-content">
            <p>Suspendisse in enim nisl. Duis nec lacus magna. Curabitur tempus metus in libero lacinia posuere. Duis accumsan bibendum dapibus. </p>
          </div>


          <div id="page-tea-layering-detail-next-arrow"></div>
          <div id="page-tea-layering-detail-prev-arrow"></div>

        </div> <!-- graph-selection-tea-mobile -->



        <div class="button-container button-container-01">
          <a href="javascript:void(0);" class="square-cta square-cta-01">save layering</a>
          <a href="#selection" class="square-cta square-cta-02">choose another layering</a>
        </div>

        <div class="button-container button-container-02">
          <a href="" class="square-cta square-cta-03">see earl grey neroli</a>
          <a href="" class="square-cta square-cta-04">see shiso mint</a>
        </div>

        

      </div>
    </div>
  </div>
</article>








<!--
   _____ ___   ___ _____ _____ ____
  |  ___/ _ \ / _ \_   _| ____|  _ \
  | |_ | | | | | | || | |  _| | |_) |
  |  _|| |_| | |_| || | | |___|  _ <
  |_|   \___/ \___/ |_| |_____|_| \_\

-->


<footer id="tea-layering-detail-footer-mobile-fixed">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-next-suggestion-container">
          <div class="page-tea-layering-detail-next-suggestion-btn">
            <span class="fa fa-arrows-h"></span>
            <h4>Next Suggestion</h4>
          </div>
        </div>

      </div>
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-other-container">
          <a href="tea-layering-landing-mobile.html" class="page-tea-layering-detail-other-btn">
            <span class="fa fa-th"></span>
            <h4>Choose Other Tea</h4>
          </a>
        </div>

      </div>
    </div>
  </div>
</footer>



<div id="tea-layering-detail-footer-mobile-spacer">
  <div class="step-01"></div>
  <div class="step-02"></div>
  <div class="step-03"></div>
  <div class="step-04"></div>
  <div class="step-05"></div>
  <div class="step-06"></div>
</div>


<footer id="tea-layering-detail-footer-mobile">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-next-suggestion-container">
          <div class="page-tea-layering-detail-next-suggestion-btn">
            <span class="fa fa-arrows-h"></span>
            <h4>Next Suggestion</h4>
          </div>
        </div>

      </div>
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-other-container">
          <a href="tea-layering-landing-mobile.html" class="page-tea-layering-detail-other-btn">
            <span class="fa fa-th"></span>
            <h4>Choose Other Tea</h4>
          </a>
        </div>

      </div>
    </div>
  </div>
</footer>






