
<!--
<div id="under-construction-disclaimer">
  <p>Home page is under-construction</p>
</div>
-->








<!--
   __  __  ___  ____ ___ _     _____
  |  \/  |/ _ \| __ )_ _| |   | ____|
  | |\/| | | | |  _ \| || |   |  _|
  | |  | | |_| | |_) | || |___| |___
  |_|  |_|\___/|____/___|_____|_____|

-->






<article id="home-mobile-landing-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div id="home-mobile-landing-copy">
          <div class="default-copy white-version">

            <a href="javascript:void(0);"  id="home-mobile-intro-logo">
              <div class="home-intro-logo-logo-mobile"></div>
              <div class="home-intro-logo-name-mobile"></div>
            </a>

            <h1>The art of <br>tea layering</h1>
            <p>Excite the palate and discover a world of simplexity tea flavours with Monogram. Exuding class and sophistication, yet playful and dynamic, explore the art of tea layering with every cup. With no two brews tasting the same, curate a personal unique identity with the world’s finest handpicked tea leaves and herbs. </p>
            <p>Get hands on and experimental with Monogram, layering the silken sachets to harmonious perfection. With each sachet carefully selected to complement each other, half the fun is to discover your very own brew. More importantly, the special bond that comes with each tea layering experience.</p>

          </div> <!-- default-copy -->
        </div> <!-- #home-mobile-landing-copy -->

        <div id="home-mobile-landing-graph-subsection">
          <div id="home-mobile-landing-graph-title">
            <h4>tea layering suggestion</h4>
          </div>
          <!-- insert graph here -->



          <!--
             __  __  ___  ____ ___ _     _____   _        _    _   _ ____ ___ _   _  ____    ____ ____      _    ____  _   _
            |  \/  |/ _ \| __ )_ _| |   | ____| | |      / \  | \ | |  _ \_ _| \ | |/ ___|  / ___|  _ \    / \  |  _ \| | | |
            | |\/| | | | |  _ \| || |   |  _|   | |     / _ \ |  \| | | | | ||  \| | |  _  | |  _| |_) |  / _ \ | |_) | |_| |
            | |  | | |_| | |_) | || |___| |___  | |___ / ___ \| |\  | |_| | || |\  | |_| | | |_| |  _ <  / ___ \|  __/|  _  |
            |_|  |_|\___/|____/___|_____|_____| |_____/_/   \_\_| \_|____/___|_| \_|\____|  \____|_| \_\/_/   \_\_|   |_| |_|

          -->

          <div id="home-mobile-landing-graph-container">

            <div id="home-mobile-landing-combination-graph" class="monogram-combination-graph">
              <div class="graph-svg"></div>                
              <div class="graph-name-overlay">
                <div class="graph-name-item floral-version"></div>
                <div class="graph-name-item creamy-version"></div>
                <div class="graph-name-item marine-version"></div>
                <div class="graph-name-item mineral-version"></div>
                <div class="graph-name-item citrus-version"></div>
                <div class="graph-name-item fruity-version"></div>
                <div class="graph-name-item sweet-version"></div>
                <div class="graph-name-item wood-version"></div>
                <div class="graph-name-item herbaceous-version"></div>
              </div>
              <div class="graph-overlay"></div>
            </div>

          </div> <!-- #home-mobile-landing-graph-container -->




          <div id="home-mobile-landing-graph-bottom">
            <div class="default-copy">

              
              <div class="graph-selection-name">
                <div id="graph-selection-name-01">
                  <h2><span style="color:#c0cdd5">Earl Grey</span> <span style="color:#d8d1ca">Neroli</span></h2>
                </div>
                <div id="graph-selection-name-02">
                  <div class="plus-sign">+</div>
                  <h2><span style="color:#c7c89b">Shiso</span> <span style="color:#bcc4b9">Mint</span></h2>
                </div>
              </div>

              <p>Fresh approach to a unique blend of mint and bergamot. An alluring experience that promises more adventure to come.</p>

              <div class="cta-container">
                <a href="javascript:void(0);" class="square-cta">buy both teas</a>
                <a href="#selection" class="square-cta">see more layering</a>
              </div>
            </div>
          </div>
        </div> <!-- #home-mobile-landing-graph-subsection -->



        <div id="home-mobile-landing-popular-subsection">
          <div id="home-mobile-landing-popular-title">
            <h4>popular tea layering</h4>
          </div>



          <div id="home-mobile-landing-popular-item-container" class="row">
            <div class="col-xs-6">

              <a href="javascript:void(0);" class="home-mobile-landing-popular-item">
                <div class="home-mobile-landing-popular-item-image">
                  <img src="http://www.monogramtea.com/skin/frontend/gryphon/gryphon_theme/images/products_svg/cherry-japonais.svg" class="parent" alt="">                              
                  <img src="http://www.monogramtea.com/skin/frontend/gryphon/gryphon_theme/images/products_svg/provencal-herbs.svg" class="overlay" alt="">
                </div>
                <div class="home-mobile-landing-popular-item-copy">

                  <div class="home-mobile-landing-popular-item-title">
                    <h2><span style="color:#c0cdd5">Earl Grey</span> <span style="color:#d8d1ca">Neroli</span></h2>
                    <div class="plus-sign">+</div>
                    <h2><span style="color:#c7c89b">Shiso</span> <span style="color:#bcc4b9">Mint</span></h2>
                  </div>
                  <h6>by monogram</h6>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada massa...</p>
                </div>
              </a>
              
            </div>
            <div class="col-xs-6">

              <a href="javascript:void(0);" class="home-mobile-landing-popular-item">
                <div class="home-mobile-landing-popular-item-image">
                  <img src="http://www.monogramtea.com/skin/frontend/gryphon/gryphon_theme/images/products_svg/cherry-japonais.svg" class="parent" alt="">                              
                  <img src="http://www.monogramtea.com/skin/frontend/gryphon/gryphon_theme/images/products_svg/uji-sencha.svg" class="overlay" alt="">
                </div>
                <div class="home-mobile-landing-popular-item-copy">

                  <div class="home-mobile-landing-popular-item-title">
                    <h2><span style="color:#c0cdd5">Earl Grey</span> <span style="color:#d8d1ca">Neroli</span></h2>
                    <div class="plus-sign">+</div>
                    <h2><span style="color:#c7c89b">Shiso</span> <span style="color:#bcc4b9">Mint</span></h2>
                  </div>

                  <h6>by monogram</h6>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque malesuada massa...</p>
                </div>
              </a>

            </div>

          </div> <!-- #home-mobile-landing-popular-item -->

          <div id="home-mobile-landing-popular-cta-container">
            <a href="http://www.monogramtea.com/store.html" class="square-cta">visit store</a>
          </div>
        </div> <!-- #home-mobile-landing-popular-subsection -->

      </div>
    </div>
  </div>
</article> <!-- home-mobile-landing-section -->



<article id="home-mobile-tea-layering-section">

  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div id="home-mobile-tea-layering-title">
          <h4>Tea Layering Suggestion</h4>
          <p>Choose a tea to see its layering suggestion.</p>
        </div>
      </div>
    </div>
  </div>


  <!--
     __  __  ___  ____ ___ _     _____   ____  ____   ___  ____  _   _  ____ _____   _     ___ ____ _____
    |  \/  |/ _ \| __ )_ _| |   | ____| |  _ \|  _ \ / _ \|  _ \| | | |/ ___|_   _| | |   |_ _/ ___|_   _|
    | |\/| | | | |  _ \| || |   |  _|   | |_) | |_) | | | | | | | | | | |     | |   | |    | |\___ \ | |
    | |  | | |_| | |_) | || |___| |___  |  __/|  _ <| |_| | |_| | |_| | |___  | |   | |___ | | ___) || |
    |_|  |_|\___/|____/___|_____|_____| |_|   |_| \_\\___/|____/ \___/ \____| |_|   |_____|___|____/ |_|

  -->


  <?php 
    $_productCollection = Mage::getModel('catalog/category')->load(92)
                         ->getProductCollection()
                         ->addAttributeToSelect('*')
                         ->addAttributeToFilter('status', 1) // enabled
                         ->addAttributeToFilter('visibility', 4) //visibility in catalog,search
                         ->addAttributeToSort('position', Varien_Data_Collection::SORT_ORDER_ASC);
    $_helper = $this->helper('catalog/output');


  ?>


  <div id="home-tea-item-container-mobile">
      <?php $count = 0; ?>
      <?php foreach ($_productCollection as $key => $_product):    
          $_imgSize = 300;
          $_imgSize2x = 600;
          $categoryIds = $_product->getCategoryIds();

          $color_arr = ["#eebec7", "#abc6ca", "#a1b2ca", "#d9d1c3", "#c7b4e3", "#f0a693", "#beced6", "#fed198", "#c2cb7e", "#f9a960", "#fa91a2", "#bac4b8"];        

          $product_name = $_product->getName();

          $product_name = strtolower($product_name);
          $product_name = str_replace(" ", "-", $product_name);
      ?>

      <a href="#graph/<?php echo $product_name; ?>" class="home-tea-item-mobile home-page-add-to-cart-mobile" id="add-to-cart-<?php echo $product_name; ?>"  data-id="<?php echo $product_name; ?>">
          <div class="home-tea-item-bg" style="background-color: <?php echo $color_arr[$count]; ?>;"></div>
          <div class="home-tea-item-text">
              <?php if(!empty($_product->getData('product_name_in_color'))): ?>
              <h2><?php echo $_product->getData('product_name_in_color') ?></h2>
              <?php else: ?>
              <h2><?php echo $_product->getName(); ?></h2>
              <?php endif; ?>


          </div>
      </a>
      <?php $count++; ?>
      <?php endforeach; ?>        
  </div> <!-- #home-tea-item-container -->

  <!--
  <script>
  $j(document).ready(function($){
      function do_update() {
          $.ajax({
              url: '/discovertea/index/cartpreview',
              dataType: 'json',
              type : 'get',
              success: function(data){

                  // update product count in cart
                  $j("#desktop-header-cart").find(".count").text("("+data.cart_qty+")");
            
              }
          });                     
      }
      $(".home-page-add-to-cart-mobile").on("click", function(e){
          e.preventDefault();

          var add_to_cart_url = $(this).attr("href");
          $.get( add_to_cart_url, function( data ) {
             do_update();
          });
      });
  });
  </script>
  -->

  <!--
     __  __  ___  ____ ___ _     _____   ____  ____   ___  ____  _   _  ____ _____   _     ___ ____ _____   _____ _   _ ____
    |  \/  |/ _ \| __ )_ _| |   | ____| |  _ \|  _ \ / _ \|  _ \| | | |/ ___|_   _| | |   |_ _/ ___|_   _| | ____| \ | |  _ \
    | |\/| | | | |  _ \| || |   |  _|   | |_) | |_) | | | | | | | | | | |     | |   | |    | |\___ \ | |   |  _| |  \| | | | |
    | |  | | |_| | |_) | || |___| |___  |  __/|  _ <| |_| | |_| | |_| | |___  | |   | |___ | | ___) || |   | |___| |\  | |_| |
    |_|  |_|\___/|____/___|_____|_____| |_|   |_| \_\\___/|____/ \___/ \____| |_|   |_____|___|____/ |_|   |_____|_| \_|____/

  -->
  
</article> <!-- home-mobile-tea-layering-section -->











<!--
    ____ ____      _    ____  _   _
   / ___|  _ \    / \  |  _ \| | | |
  | |  _| |_) |  / _ \ | |_) | |_| |
  | |_| |  _ <  / ___ \|  __/|  _  |
   \____|_| \_\/_/   \_\_|   |_| |_|

-->


<article id="tea-layering-detail-graph-section">


  <div id="tea-layering-graph-mobile" class="monogram-combination-graph">

    <div class="graph-svg"></div>                
    <div class="graph-name-overlay">
      <div class="graph-name-item floral-version"></div>
      <div class="graph-name-item creamy-version"></div>
      <div class="graph-name-item marine-version"></div>
      <div class="graph-name-item mineral-version"></div>
      <div class="graph-name-item citrus-version"></div>
      <div class="graph-name-item fruity-version"></div>
      <div class="graph-name-item sweet-version"></div>
      <div class="graph-name-item wood-version"></div>
      <div class="graph-name-item herbaceous-version"></div>
    </div>
    <div class="graph-overlay"></div>


    <!--
    <div id="combination-graph-text-container">
    </div>
    <div id="combination-graph-svg-container">
      <div id="combination-graph-svg"></div>
    </div>

    <div id="combination-graph-label">
      <div class="graph-label-image graph-label-wood"></div>
      <div class="graph-label-image graph-label-savoury"></div>
      <div class="graph-label-image graph-label-herbaceous"></div>
      <div class="graph-label-image graph-label-floral"></div>
      <div class="graph-label-image graph-label-nutty"></div>
      <div class="graph-label-image graph-label-dairy"></div>
      <div class="graph-label-image graph-label-minerality"></div>
      <div class="graph-label-image graph-label-citrus"></div>
      <div class="graph-label-image graph-label-stone-fruit"></div>
      <div class="graph-label-image graph-label-red-fruit"></div>
      <div class="graph-label-image graph-label-sweet"></div>
    </div>
    -->

  </div>
</article>


<!--
    ____ ___  ______   __
   / ___/ _ \|  _ \ \ / /
  | |  | | | | |_) \ V /
  | |__| |_| |  __/ | |
   \____\___/|_|    |_|

 -->


<article id="tea-layering-detail-copy-section">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">

        <div class="graph-selection-tea-mobile">

          <div class="graph-selection-title">
            <h4>layering suggestion <span class="number">1/4</span></h4>
          </div>

          <div class="graph-selection-name">
            <div id="graph-selection-name-01">
              <h2><span style="color:#c0cdd5">Earl Grey</span> <span style="color:#d8d1ca">Neroli</span></h2>
            </div>
            <div id="graph-selection-name-02">
              <div class="plus-sign">+</div>
              <h2><span style="color:#c7c89b">Shiso</span> <span style="color:#bcc4b9">Mint</span></h2>
            </div>
          </div>

          <div class="tea-copy-content">
            <p>Suspendisse in enim nisl. Duis nec lacus magna. Curabitur tempus metus in libero lacinia posuere. Duis accumsan bibendum dapibus. </p>
          </div>


          <div id="page-tea-layering-detail-next-arrow"></div>
          <div id="page-tea-layering-detail-prev-arrow"></div>

        </div> <!-- graph-selection-tea-mobile -->



        <div class="button-container button-container-01">
          <a href="javascript:void(0);" class="square-cta square-cta-01">save layering</a>
          <a href="#selection" class="square-cta square-cta-02">choose another layering</a>
        </div>

        <div class="button-container button-container-02">
          <a href="" class="square-cta square-cta-03" id="tea-layering-detail-copy-tea-detail-01-cta">see earl grey neroli</a>
          <a href="" class="square-cta square-cta-04"  id="tea-layering-detail-copy-tea-detail-02-cta">see shiso mint</a>
        </div>

        
        

      </div>
    </div>
  </div>
</article>








<!--
   _____ ___   ___ _____ _____ ____
  |  ___/ _ \ / _ \_   _| ____|  _ \
  | |_ | | | | | | || | |  _| | |_) |
  |  _|| |_| | |_| || | | |___|  _ <
  |_|   \___/ \___/ |_| |_____|_| \_\

-->


<footer id="tea-layering-detail-footer-mobile-fixed">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-next-suggestion-container">
          <div class="page-tea-layering-detail-next-suggestion-btn">
            <span class="fa fa-arrows-h"></span>
            <h4>Next Suggestion</h4>
          </div>
        </div>

      </div>
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-other-container">
          <a href="#selection" class="page-tea-layering-detail-other-btn">
            <span class="fa fa-th"></span>
            <h4>Choose Other Tea</h4>
          </a>
        </div>

      </div>
    </div>
  </div>
</footer>



<div id="tea-layering-detail-footer-mobile-spacer">
  <div class="step-01"></div>
  <div class="step-02"></div>
  <div class="step-03"></div>
  <div class="step-04"></div>
  <div class="step-05"></div>
  <div class="step-06"></div>
</div>


<footer id="tea-layering-detail-footer-mobile">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-next-suggestion-container">
          <div class="page-tea-layering-detail-next-suggestion-btn">
            <span class="fa fa-arrows-h"></span>
            <h4>Next Suggestion</h4>
          </div>
        </div>

      </div>
      <div class="col-xs-6">

        <div class="page-tea-layering-detail-other-container">
          <a href="tea-layering-landing-mobile.html" class="page-tea-layering-detail-other-btn">
            <span class="fa fa-th"></span>
            <h4>Choose Other Tea</h4>
          </a>
        </div>

      </div>
    </div>
  </div>
</footer>









<!--
   __  __  ___  ____ ___ _     _____   _____ ___   ___ _____ _____ ____
  |  \/  |/ _ \| __ )_ _| |   | ____| |  ___/ _ \ / _ \_   _| ____|  _ \
  | |\/| | | | |  _ \| || |   |  _|   | |_ | | | | | | || | |  _| | |_) |
  | |  | | |_| | |_) | || |___| |___  |  _|| |_| | |_| || | | |___|  _ <
  |_|  |_|\___/|____/___|_____|_____| |_|   \___/ \___/ |_| |_____|_| \_\

-->

<!-- not sure why it's not available in the home page... -->

<footer id="mobile-footer" class="visible-sm visible-xs">

  <div id="mobile-footer-copy-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">


            
          <div id="mobile-footer-copy">
            <h4>Newsletter</h4>
            <p>Get the latest news, product, announcments, promotions, and more!</p>
          </div> <!-- mobile-footer-copy -->

          <form id="mobile-newsletter-subscribe-form" class="simple-form-check">
            <div class="form-group">
              <input type="text" class="required only-email" placeholder="Enter Your Email Address">
              <input type="submit">
            </div>
          </form>

          <div id="mobile-footer-links">
            <ul>
              <li><a href="<?php echo $this->getUrl('privacy-policy'); ?>">Privacy Policy</a></li>
              <li><a href="<?php echo $this->getUrl('terms-and-conditions'); ?>">Terms & Conditions</a></li>
            </ul>
          </div>

        </div>
      </div>



    </div>
  </div> <!-- mobile-footer-copy-section -->

  <div id="mobile-footer-copyright-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">

          <div id="mobile-footer-copyright">
            <a href="<?php echo $this->getUrl('') ?>" id="mobile-footer-logo"></a>
            <h4>Monogram by Gryphon Tea Company</h4>
          </div>

        </div>
      </div>
    </div>
  </div> <!-- mobile-footer-copywrite-section -->

</footer>
