<article id="tea-layering-section-1" class="hidden-sm hidden-xs">
  <div class="desktop-header-spacer"></div>

  
  <div id="heading-text">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">

          <div id="monogram-tea-layering-title">
            <h1>monogram tea layering</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean iaculis, tellus a efficitur pellentesque, nibh arcu ultrices mi, ac commodo erat erat sit amet eros. Morbi rutrum arcu et posuere bibendum. Phasellus tristique, nisi eu dignissim semper, orci.</p>
          </div>
          
        </div>

      </div>
    </div>    
  </div>
  
  <div id="tea-layering-table">
    <div class="container-fluid">
      <div id="tea-layering-table-header" class="row">
        <div class="col-md-10 col-md-offset-1">
          <hr class="top">
        </div>
        <div class="col-md-3 col-md-offset-1 table-header-text">
          <h5>monogram teas</h5>
        </div>
        <div class="col-md-3 table-header-text">
          <h5>layering suggestions</h5>
        </div>
        <div class="col-md-4 table-header-text">
          <h5>tasting notes</h5>
        </div>
        <div class="col-md-10 col-md-offset-1">
          <hr class="bottom">
        </div>
      </div>
      <?php
      $_productCollection = Mage::getModel('catalog/category')->load(92)
                           ->getProductCollection()
                           ->addAttributeToSelect('*')
                           ->addAttributeToFilter('status', 1) // enabled
                           ->addAttributeToFilter('visibility', 4) //visibility in catalog,search
                           ->addAttributeToSort('position', Varien_Data_Collection::SORT_ORDER_ASC);
      $_helper = $this->helper('catalog/output');   
      ?>

      <?php foreach ($_productCollection as $key => $_product):            
          $product_name = $_product->getName();

          $product_name = strtolower($product_name);
          $product_name = str_replace(" ", "-", $product_name);

          $name_id_arr = [
            'cherry-japonais'=>'1', 
            'uji-sencha'=>'2', 
            'jasmine-silk-pearls'=>'3', 
            'milky-oolong'=>'4',
            'lapsang-florale'=>'5',
            'kashmere'=>'6',
            'earl-grey-neroli'=>'7',
            'morning-english'=>'8',
            'provencal-herbs'=>'9',
            'saffronais'=>'10',
            'rose-of-ariana'=>'11',
            'shiso-mint'=>'12'
          ];
      ?>
      <div class="row tea-layering-table-contents">
        <div class="col-md-3 col-md-offset-1 tea-layering-table-text">
          <?php if(!empty($_product->getData('product_name_in_color'))): ?>
          <a href="/tea-matrix#<?php echo $name_id_arr[$product_name]; ?>"><h3><?php echo $_product->getData('product_name_in_color') ?></h3></a>
          <?php else: ?>
          <a href="/tea-matrix#<?php echo $name_id_arr[$product_name]; ?>"><h3><?php echo $_product->getName(); ?></h3></a>
          <?php endif; ?>
        </div>
        <div class="col-md-7">
          <?php 
          $object = Mage::getModel('catalog/product');
          $upsell_product = $_product->getUpSellProductCollection()->addAttributeToSort('position', Varien_Db_Select::SQL_ASC)->addStoreFilter();
          $count = 1;
          foreach($upsell_product as $_upsell):
            //get detail of single upsell prdocut using upsell product id
            $upsp = $object->load($_upsell->getId());

            $upsp_name = $upsp->getName();
            $upsp_name = strtolower($upsp_name);
            $upsp_name = str_replace(" ", "-", $upsp_name);
          ?>      
          <div class="row">
            <div class="col-md-5 tea-layering-table-text">
              <?php 
                $child_product_name = $upsp->getName();
                $child_product_name = strtolower($child_product_name);
                $child_product_name = str_replace(" ", "-", $child_product_name);
              ?>
              <?php if(!empty($upsp->getData('product_name_in_color'))): ?>
              <a href="/tea-matrix#<?php echo $name_id_arr[$child_product_name]; ?>"><h3><?php echo $upsp->getData('product_name_in_color') ?></h3></a>
              <?php else: ?>
              <a href="/tea-matrix#<?php echo $name_id_arr[$child_product_name]; ?>"><h3><?php echo $upsp->getName(); ?></h3></a>
              <?php endif; ?>
            </div>
            <div class="col-md-6 tea-layering-table-text">
              <div class="tea-layering-text">
                <a href="/#graph/<?php echo $product_name; ?>/<?php echo $upsp_name; ?>" class="tea-layering-text-link">See Layering Suggestions >></a>
                <span><?php echo $upsp->getDescription(); ?></span>
              </div> 
            </div>
          </div>
          <?php
            $count++;
          endforeach; 
          ?>    
        </div>        
        <div class="col-md-10 col-md-offset-1"><hr class="bottom"></div>
      </div>
      <?php endforeach; ?>   


    </div>
  </div>

  <div class="desktop-header-spacer" style="height: 100px;"></div>
</article>     

<article id="home-mobile-tea-layering-section">

  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div id="home-mobile-tea-layering-title">
          <h4>Tea Layering Suggestion</h4>
          <p>Choose a tea to see its layering suggestion.</p>
        </div>
      </div>
    </div>
  </div>


  <!--
     __  __  ___  ____ ___ _     _____   ____  ____   ___  ____  _   _  ____ _____   _     ___ ____ _____
    |  \/  |/ _ \| __ )_ _| |   | ____| |  _ \|  _ \ / _ \|  _ \| | | |/ ___|_   _| | |   |_ _/ ___|_   _|
    | |\/| | | | |  _ \| || |   |  _|   | |_) | |_) | | | | | | | | | | |     | |   | |    | |\___ \ | |
    | |  | | |_| | |_) | || |___| |___  |  __/|  _ <| |_| | |_| | |_| | |___  | |   | |___ | | ___) || |
    |_|  |_|\___/|____/___|_____|_____| |_|   |_| \_\\___/|____/ \___/ \____| |_|   |_____|___|____/ |_|

  -->


  <?php 
    $_productCollection = Mage::getModel('catalog/category')->load(92)
                         ->getProductCollection()
                         ->addAttributeToSelect('*')
                         ->addAttributeToFilter('status', 1) // enabled
                         ->addAttributeToFilter('visibility', 4) //visibility in catalog,search
                         ->addAttributeToSort('position', Varien_Data_Collection::SORT_ORDER_ASC);
    $_helper = $this->helper('catalog/output');


  ?>


  <div id="home-tea-item-container-mobile">
      <?php $count = 0; ?>
      <?php foreach ($_productCollection as $key => $_product):    
          $_imgSize = 300;
          $_imgSize2x = 600;
          $categoryIds = $_product->getCategoryIds();

          $color_arr = ["#eebec7", "#abc6ca", "#a1b2ca", "#d9d1c3", "#c7b4e3", "#f0a693", "#beced6", "#fed198", "#c2cb7e", "#f9a960", "#fa91a2", "#bac4b8"];        

          $product_name = $_product->getName();

          $product_name = strtolower($product_name);
          $product_name = str_replace(" ", "-", $product_name);
      ?>

      <a href="<?php echo $this->getUrl('/'); ?>#graph/<?php echo $product_name; ?>" class="home-tea-item-mobile home-page-add-to-cart-mobile" id="add-to-cart-<?php echo $product_name; ?>"  data-id="<?php echo $product_name; ?>">
          <div class="home-tea-item-bg" style="background-color: <?php echo $color_arr[$count]; ?>;"></div>
          <div class="home-tea-item-text">
              <?php if(!empty($_product->getData('product_name_in_color'))): ?>
              <h2><?php echo $_product->getData('product_name_in_color') ?></h2>
              <?php else: ?>
              <h2><?php echo $_product->getName(); ?></h2>
              <?php endif; ?>


          </div>
      </a>
      <?php $count++; ?>
      <?php endforeach; ?>        
  </div> <!-- #home-tea-item-container -->
  
</article> <!-- home-mobile-tea-layering-section -->
<script>
  $j('body').addClass("mobile-home-tea-layering-version");
</script>